<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3b0a2872-1ea4-4bf4-8ee9-599112f865e6</testSuiteGuid>
   <testCaseLink>
      <guid>0ec17562-e2d4-4cb9-9ddc-012be282ffde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/Login/TC01 Verify Enter Email Screen UI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36ef3fbf-acd8-4c4d-9a7a-9a76b910ed78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>799e8f76-66fe-424a-9646-a6153201c681</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88f4c3bf-70c2-41a7-8db7-ed8fc1b7b42d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>faf38192-959b-4fc3-8b99-2b9714fd6cac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/Login/TC02 Verify Error Message On Email Screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a760e21-85be-4d0f-990f-fdbf86c131c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f703d883-aa5b-437c-9b9c-724271e0427b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eae5b4ca-1525-4dba-8318-df22cf54e9b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b03e78ce-aff1-4b8c-8117-6cf00ba89194</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/Login/TC03 Verify Enter Password Screen UI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dcfe9dd-d819-4ad6-b708-f7e444eafec8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c11eccbf-baa6-4112-8957-34c4e7be2b16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13acb8eb-ed9e-45e7-8710-141fdc4e6277</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56b2d3ca-ed67-44f9-b99d-e892d06e8991</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea313e4b-dccd-4585-899f-11b50366ba3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/Login/TC04 Verify Error Message On Password Screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2dcbf00-2726-46ae-bd16-e736445a3f20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e5942ed-c59d-4a4f-8f68-88452fac6d2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>382af9f2-dfda-4d8a-9ff7-41b2f86ef64f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f32ebaf-894d-42bf-b206-cf5e32113a4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bfd0b26-fa46-4985-b2bc-2bd0a0ef8258</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8fdecc1-ab4f-49f8-a4ee-ba424a0d6bb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/Login/TC05 Validate Back Arrow On Password And Email Screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abce8178-41b0-4dba-ade0-c56dea37f3e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24a117dd-4c50-4018-8e88-7ae566059f63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/Login/TC06 Verify User Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bc3f581-ed5b-43b6-94f1-312553e318ac</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
