<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SignupSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e97e7e4e-68fb-4262-9782-b1cf6c5cf6af</testSuiteGuid>
   <testCaseLink>
      <guid>97cecdbe-3731-46e1-ad03-09e6252dcebb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/Signup/TC04 Verify Signup Screen UI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22ce963a-dad5-4fa5-b638-ff93d2dabe3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03665408-18d6-4453-8936-cd1831974057</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5ae3d1a-f128-4888-84e4-37e9e9bc6339</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/Signup/TC05 Verify Error Message On Signup Screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>302ac7ca-2de3-4bcd-8da7-25337aa6cc92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d7f29b8-350b-4c01-bece-58732b55f6c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e71a31e3-e4c4-4cad-ac72-4221fe3ef1ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/Signup/TC06 Verify User Signup</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>153c69dc-0a1c-4884-878e-872fddf22625</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74476f03-8f65-4ddd-b059-2d796305ba2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92cfad78-6621-4136-ab2c-9fd90e9df8e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f57282e-5943-435c-8d23-2a9e3c140120</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
