<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UserProfileSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ebf13f1c-8e8e-449a-9195-c8832e143d16</testSuiteGuid>
   <testCaseLink>
      <guid>66f6cb27-57a9-48d9-b3c7-f4b99fabfd06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/User Profile/TC08 Verify User Logout Popup UI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7ab2b13-da6d-4306-9ff3-87ed940eea8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e7abaa5-cb44-446a-acc4-9980c1b3fa7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e522e67-c5e4-4480-8c28-3f4d1bc890f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffd84ccc-3160-4f23-954f-04a8fd81d0ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>906d2278-1cdc-4166-8d94-815a2896e089</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/User Profile/TC09 Verify User Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce4eeb55-19e0-4675-a6fa-9fe6f42b363c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5a9f2e9-7307-4796-a725-da5d008f70be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/User Profile/TC10 Verify User Can Edit User Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79dbf75a-1f1b-47f1-9b14-f7178e153e45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>260bb5ad-4ccf-4fe0-a546-761bf29c89f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e87cf1b2-7576-475d-8594-142840dce991</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/User Profile/TC11 Verify Confirmation Popup for User name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feb16d1c-11b1-4b72-9bc2-d43e71a9f60e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cdc1ecb-b2db-4b69-8d38-e965ae22c930</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>748aaa81-e5e1-4468-a465-d34eee91d528</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7be2655-5d84-41ed-9c00-eef94a61b000</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2779e54-3b1d-42e8-815c-25c7ed6c2c58</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/User Profile/TC12 Verify Error Message On Change Password Screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d11cbd7c-b321-4ded-95c6-bc6d8de3114e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bea96145-3619-44c4-9b98-c611921a3111</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9605b71c-33e8-44c6-9995-3dbf368eae68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b83d2f86-6785-446b-b599-e8b040da8dd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c463119-fb6d-42cd-b8da-d309b6c7986f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cd8dba9-36ae-4df8-af05-8fbb09ba27a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0126eb55-6d8e-4266-bdf3-3809f8148531</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16d5c584-9b89-45b0-8977-9638fa6a85fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/User Profile/TC13 Verify User Can Change User Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b9997c3-f1d2-48b0-8789-bd8004bbe457</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2c43445-b409-4958-b622-523ed2864a32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49b13080-edd4-4d1e-8d21-3894916fecfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/mobile/User Profile/TC14 Verify User Can Update Profile Photo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32510e61-cb9b-42d8-8347-e91f75640453</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47bc60e8-c114-412e-899c-6a4622057790</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
