<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_User select action</name>
   <tag></tag>
   <elementGuidId>da5dee65-ef36-4567-b58e-c7749b3710c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'${name}')]/ancestor::div[@class='card cardsUI']//button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#grid #dropdown-basic >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3e4f76ae-5aa8-4f9e-b66a-9481fc99b597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-ellipsis-h</value>
      <webElementGuid>d6fb7386-aab7-4ca3-8dbb-04e6e4fec1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03fcdf69-0aac-413d-8cbc-f145f303b9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/div[1]/div[1]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;kaif mx-2 mb-3&quot;]/div[@class=&quot;card cardsUI&quot;]/div[@class=&quot;view overlay&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/div[@class=&quot;threedots&quot;]/div[@class=&quot;dropdown&quot;]/button[@id=&quot;dropdown-basic&quot;]/i[@class=&quot;fa fa-ellipsis-h&quot;]</value>
      <webElementGuid>e91c3f6d-146b-4acb-9db7-f8bb89d91c5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='dropdown-basic']/i)[2]</value>
      <webElementGuid>ce0fd5d5-ed39-4f8e-9365-6b8f6c4f66f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/button/i</value>
      <webElementGuid>6504b9c0-85dd-4fe6-969e-d7545af1c70a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
