<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Add employee</name>
   <tag></tag>
   <elementGuidId>e0db7fb8-91e5-4e93-bd8b-688227e25133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div[6]/div/div[3]/a/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a>button.AddEmp_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add Employee&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c22f8123-c7ba-4f00-a2b0-051177d4be97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>exportIcon1</value>
      <webElementGuid>96533919-6abd-4d3b-9694-aaa77e94f651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAdCAYAAAC9pNwMAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFpSURBVHgBzZaBUcMwDEW/ex2gTNBsQDdoRmAD2CBsEDYAJqAbwAaBCUonIExANhDSxb3mjBNbNrn23enaWrJkq7YsYAQi2rI0LD/UI99vMSccoKZxasyB3WmILTJZeMbuEeYmZMCLq1heEAsb7yN23ET4aazt2qdf4Ez4Ar8hzA6Z+AI/s7QTc0T3jkyW7oAxpuP/RQ6P7LzwBC3Z5ns4yPbX/LFybI+/N6wvHN3BYAJbMDbWyYcsRhbm2Ih+Dx0PBv+AXB383fEd+ow9sXSOboe5uNjrtPQN8iolbVIW3fS1Iu7hyoZOL1Kwco2lcOBrMtVDw5r01BP+Hlm+QkErSqdCCjyxoNNjn4LMXWnjyqn23UENK+tDHbhEPiWUGMkV8un4il1pJpz1PW6RTwslEjjm4Q/xCS0U11WGWCMF6qtMKnl9Njt4JT3x7WsgeB0ZUKpVWqm0GE/wAv2TeGx5hkgncYCnBdLyC8d1wEr51N6+AAAAAElFTkSuQmCC</value>
      <webElementGuid>f75ef247-41a2-4cbd-ac9d-bb80b0e62c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-md-12 d-flex mb-4&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/div[3]/a[1]/button[@class=&quot;btn AllHandsEmployeeEventBtn AddEmp_btn&quot;]/img[@class=&quot;exportIcon1&quot;]</value>
      <webElementGuid>af6fae6c-607f-412e-9886-a8d442a4cdda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div[6]/div/div[3]/a/button/img</value>
      <webElementGuid>2150b96d-b6ff-42c9-a88d-b0889bf6460c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAdCAYAAAC9pNwMAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFpSURBVHgBzZaBUcMwDEW/ex2gTNBsQDdoRmAD2CBsEDYAJqAbwAaBCUonIExANhDSxb3mjBNbNrn23enaWrJkq7YsYAQi2rI0LD/UI99vMSccoKZxasyB3WmILTJZeMbuEeYmZMCLq1heEAsb7yN23ET4aazt2qdf4Ez4Ar8hzA6Z+AI/s7QTc0T3jkyW7oAxpuP/RQ6P7LzwBC3Z5ns4yPbX/LFybI+/N6wvHN3BYAJbMDbWyYcsRhbm2Ih+Dx0PBv+AXB383fEd+ow9sXSOboe5uNjrtPQN8iolbVIW3fS1Iu7hyoZOL1Kwco2lcOBrMtVDw5r01BP+Hlm+QkErSqdCCjyxoNNjn4LMXWnjyqn23UENK+tDHbhEPiWUGMkV8un4il1pJpz1PW6RTwslEjjm4Q/xCS0U11WGWCMF6qtMKnl9Njt4JT3x7WsgeB0ZUKpVWqm0GE/wAv2TeGx5hkgncYCnBdLyC8d1wEr51N6+AAAAAElFTkSuQmCC')]</value>
      <webElementGuid>d751cec1-5a16-4380-9ad7-9e70ce9863d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button/img</value>
      <webElementGuid>44aa7433-a384-4ed4-bbb1-110bbe1ce9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAdCAYAAAC9pNwMAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFpSURBVHgBzZaBUcMwDEW/ex2gTNBsQDdoRmAD2CBsEDYAJqAbwAaBCUonIExANhDSxb3mjBNbNrn23enaWrJkq7YsYAQi2rI0LD/UI99vMSccoKZxasyB3WmILTJZeMbuEeYmZMCLq1heEAsb7yN23ET4aazt2qdf4Ez4Ar8hzA6Z+AI/s7QTc0T3jkyW7oAxpuP/RQ6P7LzwBC3Z5ns4yPbX/LFybI+/N6wvHN3BYAJbMDbWyYcsRhbm2Ih+Dx0PBv+AXB383fEd+ow9sXSOboe5uNjrtPQN8iolbVIW3fS1Iu7hyoZOL1Kwco2lcOBrMtVDw5r01BP+Hlm+QkErSqdCCjyxoNNjn4LMXWnjyqn23UENK+tDHbhEPiWUGMkV8un4il1pJpz1PW6RTwslEjjm4Q/xCS0U11WGWCMF6qtMKnl9Njt4JT3x7WsgeB0ZUKpVWqm0GE/wAv2TeGx5hkgncYCnBdLyC8d1wEr51N6+AAAAAElFTkSuQmCC']</value>
      <webElementGuid>dbc74edb-82e2-4a99-91ff-8011544c4170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
