<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_Grade</name>
   <tag></tag>
   <elementGuidId>af357d05-f213-4cf7-8421-301d09293273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gradeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gradeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;gradeId&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e0d9f4b2-8d91-46d6-888e-843834477a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gradeId</value>
      <webElementGuid>22756855-115b-49ab-9a03-405f875e49cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-3 height</value>
      <webElementGuid>528ff5f6-68af-4a7f-80b6-0a0b5b62153b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gradeId</value>
      <webElementGuid>4e80bdd6-35c8-4603-9c4c-253c59900cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>gradeId</value>
      <webElementGuid>94b530ba-ae18-46ea-a25c-5ccded7c3bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select...L1</value>
      <webElementGuid>bb0f4a1d-c5be-443f-9401-a5a87590b3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gradeId&quot;)</value>
      <webElementGuid>ef38c6a7-1193-49f4-b039-100f38ab0438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gradeId']</value>
      <webElementGuid>a717df88-daf6-4dad-a4b2-7c9bdfc656af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='empDetails']/div/div/div/div/div[2]/div[2]/div/div/select</value>
      <webElementGuid>01367586-9c04-4af9-877e-2fb8b2915607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>91bf0cbc-83ed-4b56-b23b-3de708c1700e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Probation Period (Days)'])[1]/preceding::select[1]</value>
      <webElementGuid>9fb9784d-1894-4bd1-a4bc-84a02a59175c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[2]/div/div/select</value>
      <webElementGuid>a2bdf0f0-8749-4779-96f9-1319528b0abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gradeId' and @name = 'gradeId' and (text() = 'Select...L1' or . = 'Select...L1')]</value>
      <webElementGuid>b06b6a14-55d1-449a-9b0b-4b1923016b87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
