<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_Select emp series</name>
   <tag></tag>
   <elementGuidId>5613ff9a-b685-4e94-9d30-ebae2539a74c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='employeeSeriesId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#employeeSeriesId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;employeeSeriesId&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a06a501a-6d6c-419e-8920-1c9087424230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cursorview mt-3 height</value>
      <webElementGuid>dd3eff7f-7dbc-4b61-bd20-81b881dffaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employeeSeriesId</value>
      <webElementGuid>f8819436-6e65-4bca-a827-5289412133ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employeeSeriesId</value>
      <webElementGuid>2dbd09ca-afa5-4b47-8b9d-e7a957decddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>employeeSeriesId</value>
      <webElementGuid>2d81e3db-01b0-45c4-8450-ff6466ce670a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Select-permanent</value>
      <webElementGuid>80abee1e-afe5-464b-ab0e-122b0ad1b544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeSeriesId&quot;)</value>
      <webElementGuid>385935a2-0959-4b55-80fd-6af4132285ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='employeeSeriesId']</value>
      <webElementGuid>fbd4fca8-563c-42ef-8916-7c16b8a846de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='empDetails']/div/div/div/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>112d6c98-4b5f-40c3-b949-878c275d45b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>f5487591-ab2c-4bdb-abd9-8ff35df9bb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>0c90861d-cd70-458c-988d-89df3af60f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>2a19374e-7bda-488a-8af1-b6e49ebdb6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'employeeSeriesId' and @name = 'employeeSeriesId' and (text() = '-Select-permanent' or . = '-Select-permanent')]</value>
      <webElementGuid>943ac071-dafb-4736-a649-67c8111b584b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
