<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdowm_RM</name>
   <tag></tag>
   <elementGuidId>51b20a2b-14bc-413b-9077-c14a9bea76d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='reportingManagerId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reportingManagerId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;reportingManagerId&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fb467217-6906-495c-b3e1-a5391442525c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reportingManagerId</value>
      <webElementGuid>8740c676-ccb4-4d34-8f62-3ce9cb951b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>reportingManagerId</value>
      <webElementGuid>8e926618-06cd-4e93-9d53-4193ea6fe74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reportingManagerId</value>
      <webElementGuid>c13e8925-6418-4dbd-90f2-89bc2c51bc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cursorview mt-3 height</value>
      <webElementGuid>a2da5880-8215-4a94-8d1f-e31b1728822c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Select-First NameNew User</value>
      <webElementGuid>608330fc-3023-49fc-80f3-072ac2e11124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportingManagerId&quot;)</value>
      <webElementGuid>0afeec9c-46ab-4cae-b806-4f4d52c26c55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='reportingManagerId']</value>
      <webElementGuid>4600a38e-6676-41d0-bf19-e80899c26d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='empDetails']/div/div/div/div/div[2]/div[3]/div/div/select</value>
      <webElementGuid>fefdd1e1-12c7-41ad-9299-72bfa97dd1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::select[1]</value>
      <webElementGuid>b940357e-ab7a-4d7f-9d0c-b96b60a3d1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/preceding::select[1]</value>
      <webElementGuid>d76f2949-6082-4c03-b4b5-058718f290a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>842d0d58-e63c-4ae7-ac5f-a8c1193b1fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'reportingManagerId' and @name = 'reportingManagerId' and (text() = '-Select-First NameNew User' or . = '-Select-First NameNew User')]</value>
      <webElementGuid>a5382751-be3d-4c12-91ee-03a47fe54afd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
