<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Enter employee name</name>
   <tag></tag>
   <elementGuidId>e48b9043-d39e-4c3f-b7f0-22be07145b73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='name'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Employee Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a33eed56-97dd-4a24-bc5b-bd2f82200a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cursorview mt-3 height</value>
      <webElementGuid>90061f3c-d214-47a9-b871-0a5677c344ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Employee Name</value>
      <webElementGuid>e767d666-5770-43e2-a8c9-bb5c1c256a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>7fb6d9fd-32ca-4b1a-8d10-41bdf3a74c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>0c0507cb-8354-4938-b02e-502d3ea81729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>38434407-c496-413e-bd31-e997e243ebc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personalInfo&quot;)/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;container-fluid mt-2 my-profile-section&quot;]/div[@class=&quot;card cards-section&quot;]/div[@class=&quot;p-3 cardpadding&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;col-md-6&quot;]/input[@id=&quot;name&quot;]</value>
      <webElementGuid>dd46f6c1-8de0-45c3-b259-c7ede22a1318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name']</value>
      <webElementGuid>8b3aed41-e3f8-43d9-b616-974bf0b827f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalInfo']/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>47aefcd7-362a-472f-99ec-18064b2adeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>045b746b-beed-4b8b-883f-8fe657b4cb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Employee Name' and @id = 'name' and @name = 'name']</value>
      <webElementGuid>7a26791c-36b8-49cf-8e22-1e62add2e4f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
