<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IMG_Google icon</name>
   <tag></tag>
   <elementGuidId>59f3c690-d9a1-4649-a5f1-0c4a7014c6d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/form/div[9]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.loginwithgooglebtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;form&quot;] div >> internal:has-text=&quot;Or Signup with&quot;i >> div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>557c8261-84fa-46db-b2b5-28acb85fd549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginwithgooglebtn</value>
      <webElementGuid>f4fbf410-6e80-44a2-b124-6e4c4ab6241e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;register-main-container&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;register-flex-container&quot;]/div[@class=&quot;register-form-container fw-bolder d-flex flex-column justify-content-center align-items-center&quot;]/div[@class=&quot;registerformdiv&quot;]/form[@class=&quot;d-flex flex-column align-items-center justify-content-between registerform&quot;]/div[@class=&quot;register-footer-container&quot;]/div[@class=&quot;google-container&quot;]/div[@class=&quot;loginwithgooglebtn&quot;]</value>
      <webElementGuid>3cf7a1f1-f6bf-4405-8596-44b07191ac06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/form/div[9]/div/div</value>
      <webElementGuid>9fd7067b-734d-4bde-b0e7-216e3b104eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or Signup with'])[1]/following::div[2]</value>
      <webElementGuid>a840f0fb-2a5c-4492-ad45-4374fd4ef22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an account'])[1]/following::div[3]</value>
      <webElementGuid>27298ff2-2a8a-44c5-a987-be4500bb5f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div</value>
      <webElementGuid>bf7a637a-e5fb-40de-9371-937f0d7e116b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
