<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Confirm password</name>
   <tag></tag>
   <elementGuidId>72843bb1-b626-4738-b5b2-d27335d559cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='confirmPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='confirmPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Confirm Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bb1556d-fc3f-4bc1-a923-73ac3b9da14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>registerfield pass_input  w-100</value>
      <webElementGuid>1f63d615-a9a2-4823-8396-82fd5f8c1004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Confirm Password</value>
      <webElementGuid>ec1c4f5b-c9c7-4961-b302-492b28103931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>3243508c-552c-4984-8263-459ad07a0361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>86dbcaf1-2b92-438d-b4c0-0ba5f6b653a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>46fcaa77-b5e1-48c0-b308-050e91700e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;register-main-container&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;register-flex-container&quot;]/div[@class=&quot;register-form-container fw-bolder d-flex flex-column justify-content-center align-items-center&quot;]/div[@class=&quot;registerformdiv&quot;]/form[@class=&quot;d-flex flex-column align-items-center justify-content-between registerform&quot;]/div[@class=&quot;form-group  w-100 my-2 position-relative&quot;]/div[@class=&quot;input-group fieldgroupc&quot;]/input[@class=&quot;registerfield pass_input  w-100&quot;]</value>
      <webElementGuid>f8f67eac-8eff-4cea-9381-c6c57782b1bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='confirmPassword']</value>
      <webElementGuid>046fc7b6-631d-4549-9013-e93d21f5a119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/form/div[5]/div/input</value>
      <webElementGuid>9b30b508-d9eb-4435-a5b5-1146bd2708fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>00e37e4f-29c1-44cc-82c3-fb0e10478648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Confirm Password' and @name = 'confirmPassword' and @type = 'password']</value>
      <webElementGuid>980b67cd-d119-4984-bc13-39d28b8e9447</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
