<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_User Email</name>
   <tag></tag>
   <elementGuidId>8d0f2957-390e-4f78-83d7-43b871819c85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;email&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74336236-8fa3-47e2-b668-9c4c3acd0f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4c3caebd-5542-46a7-bbe0-7edec9814ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f1ddbc7a-29a6-4126-ad5d-4f4e98cefdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>registerfield email w-100</value>
      <webElementGuid>5bbec334-0e27-4298-ad01-645753a0b4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>c2c120d0-6b45-497c-97c2-211cb604716b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c586b644-542f-40ff-aeaf-b6f9b510ab16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;register-main-container&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;register-flex-container&quot;]/div[@class=&quot;register-form-container fw-bolder d-flex flex-column justify-content-center align-items-center&quot;]/div[@class=&quot;registerformdiv&quot;]/form[@class=&quot;d-flex flex-column align-items-center justify-content-between registerform&quot;]/div[@class=&quot;d-flex my-2 w-100&quot;]/input[@class=&quot;registerfield email w-100&quot;]</value>
      <webElementGuid>a2457dc0-1312-4c6d-a4c9-2d92e1ba7736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>feb0d762-d61b-4ba9-8d91-5e376b757a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/form/div[2]/input</value>
      <webElementGuid>22cecbd4-89d4-41f1-b99b-26e8d4e99d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4fbdd905-7829-4b4a-8dd9-9593f1717d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @placeholder = 'Email Address']</value>
      <webElementGuid>53caa6b0-eaab-4b9c-b08f-eb81718365de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
