<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_Product url</name>
   <tag></tag>
   <elementGuidId>f9b97c47-5239-41c2-96e0-486511c4571c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/form/div[6]/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.mobilefield</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;.clovehr.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>17fbc997-38c3-4737-90f8-d5538bc60385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobilefield</value>
      <webElementGuid>14da0194-ef54-4c61-8dc5-8bbcd04b8000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.clovehr.com</value>
      <webElementGuid>9c624499-f7b5-4ce0-987f-f334ebec278b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;register-main-container&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;register-flex-container&quot;]/div[@class=&quot;register-form-container fw-bolder d-flex flex-column justify-content-center align-items-center&quot;]/div[@class=&quot;registerformdiv&quot;]/form[@class=&quot;d-flex flex-column align-items-center justify-content-between registerform&quot;]/div[@class=&quot;form-group w-100 my-2 position-relative&quot;]/div[@class=&quot;input-group fieldgroupc&quot;]/div[@class=&quot;lblLoginForm domain-text&quot;]/p[@class=&quot;mobilefield&quot;]</value>
      <webElementGuid>6fa94c21-d2b4-475d-bf3d-27e4ea7382a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/form/div[6]/div/div/p</value>
      <webElementGuid>42a8d4e8-0755-41cd-9faf-f8cb51c5d7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create your account'])[2]/following::p[2]</value>
      <webElementGuid>778f5af2-f809-4e0b-87c5-96af307ee3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create your account'])[1]/following::p[2]</value>
      <webElementGuid>25fd2c58-b58c-4ff1-abc5-251ddd59e1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy of CloveHRMS'])[1]/preceding::p[1]</value>
      <webElementGuid>f3582d77-152a-43b0-981f-2b85170931db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='.clovehr.com']/parent::*</value>
      <webElementGuid>f2b6d4e5-9487-4eea-a865-cc262b575cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/p</value>
      <webElementGuid>e9a68467-d8da-4b9a-8b19-72c45ad2142c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '.clovehr.com' or . = '.clovehr.com')]</value>
      <webElementGuid>51d45c43-2651-49bc-9292-70c2b0fb2311</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
