<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Profile Menu</name>
   <tag></tag>
   <elementGuidId>170f4c89-896d-4698-8b64-fdcc160b4ffc</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[aria-label*='profile']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/header/div/div/div/section/button/div/div</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Go to your profile&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b047852-ca8b-4f30-b165-33931837ae3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dn_c</value>
      <webElementGuid>6c72820c-174a-4de4-bb60-e0d7c21ffba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Wildest Profile Icon</value>
      <webElementGuid>1ae5d3ec-5819-4d60-b8bb-47eca08f5ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;F_c&quot;]/header[1]/div[@class=&quot;bd_ft&quot;]/div[@class=&quot;bd_mM&quot;]/div[@class=&quot;bd_mP&quot;]/section[@class=&quot;bd_mQ&quot;]/button[@class=&quot;bd_hF&quot;]/div[@class=&quot;bd_hZ&quot;]/div[@class=&quot;dn_c&quot;]</value>
      <webElementGuid>2704dc9c-dc38-4ee3-82c3-71d564f0b8f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/header/div/div/div/section/button/div/div</value>
      <webElementGuid>610a51ec-451d-4266-83c5-e47e83dea141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='opens in a new tab'])[1]/following::div[3]</value>
      <webElementGuid>3fcb7469-2da9-4e1c-a855-2b2ced1623bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::div[2]</value>
      <webElementGuid>9ebe7a3c-7f28-45b5-aa66-a45d87ed0e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL'])[1]/preceding::div[3]</value>
      <webElementGuid>a182eba8-ad87-4504-a7a1-30c5b3074b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div</value>
      <webElementGuid>307ac0cf-c7ef-49a4-a859-6cc58e35fa74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'The Wildest Profile Icon' or . = 'The Wildest Profile Icon')]</value>
      <webElementGuid>93bcdefc-369c-47d8-a977-20cf76d6e927</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
