<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Error_Popup email field</name>
   <tag></tag>
   <elementGuidId>4d638224-2d0c-4ef9-8cd9-d91887e45618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span#email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c2541338-6d9f-4ba9-a3cf-51928e033063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1713349588062</value>
      <webElementGuid>7a33e4c8-fba2-49c2-98fd-96437fbd6f33</webElementGuid>
   </webElementProperties>
</WebElementEntity>
