<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Search Input</name>
   <tag></tag>
   <elementGuidId>6d576c8e-5a84-4c17-af05-7f57dcfd5c0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#wildest-input-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wildest-input-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13dd1a1b-3754-40bd-8761-0b3c630b24d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bY_qG</value>
      <webElementGuid>774a6ff9-6522-468a-840b-7a26c209f2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ff4e9390-a120-442b-9ce4-af0f65bdbe7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wildest-input-search</value>
      <webElementGuid>6b89903e-396c-41c2-87cb-f9c989fec017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wildest-input-search&quot;)</value>
      <webElementGuid>a8cfd9bc-e52e-4c98-a0a0-03932e56ce13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wildest-input-search']</value>
      <webElementGuid>f594b5ca-5a2f-4a7c-b108-8270cb2d35b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/header/div/div[2]/form/input</value>
      <webElementGuid>ccb2153c-888f-4a1f-b086-e6c3dbc6bdef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>edca8de5-c997-46f4-a9f1-54fdb86d1373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'wildest-input-search']</value>
      <webElementGuid>58f3d9fd-d55a-45b4-bd1d-7720df880296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
