<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Email input field</name>
   <tag></tag>
   <elementGuidId>db48b523-8df7-46f4-b370-10a76f4c0527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>4fcdbfbe-eaec-4c4b-a0c6-5bfd8c35485d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1713349311678</value>
      <webElementGuid>95273d43-92bd-4ac6-a44c-cc940026e697</webElementGuid>
   </webElementProperties>
</WebElementEntity>
