<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IMG_Login Page</name>
   <tag></tag>
   <elementGuidId>6a795443-d638-4c50-9930-080b48d9ae52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.login-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>70134b8d-0e3f-4b19-96e6-e026a70f0c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-icon</value>
      <webElementGuid>3b2a2163-4ba1-4cd4-b54f-281fc2baa2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/register-icon.40d70054.svg</value>
      <webElementGuid>c7b9392a-9cfe-4166-9fa3-8a36d0d02dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;login-main-container&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;login-flex-container&quot;]/img[@class=&quot;login-icon&quot;]</value>
      <webElementGuid>9a158af3-2da0-4630-97f3-f068305bcc36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/img</value>
      <webElementGuid>c34743e9-54d6-4959-95b9-53669550ff55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>231a8727-68a9-4cb2-97ec-246a8a92ad99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/register-icon.40d70054.svg']</value>
      <webElementGuid>7bc439b5-2aa2-4b87-8201-822bff33ce2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
