<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Logout</name>
   <tag></tag>
   <elementGuidId>97e46b9d-81de-4153-b93b-b6eb1a41bc52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>:nth-child(2) div.headling-left-panel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-5']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Logout&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>28a55132-40e3-4d24-a90b-f54e01e6fca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-10 text-left mt-1 headling-left-panel</value>
      <webElementGuid>48195bce-cf6f-4fad-94aa-7f236a014834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>ea0ba85c-0816-4514-ad36-50779ff3b818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-5&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 d-flex&quot;]/div[@class=&quot;col-md-10 text-left mt-1 headling-left-panel&quot;]</value>
      <webElementGuid>751bcd7a-5032-40a5-9783-6ab8077db018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mui-5']/div/div/div[2]</value>
      <webElementGuid>78960054-d68c-4400-b4fe-c410415e66b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/following::div[4]</value>
      <webElementGuid>a147b701-01d7-49a3-953e-3e9734087d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[8]</value>
      <webElementGuid>0f1e804f-cf73-4ba1-a920-0c57c3eea70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>bb688a88-68c2-4d98-8e4d-db7302884041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]</value>
      <webElementGuid>8cb00235-0f00-4945-b3de-e3a5bafe2f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>1eb55945-ac04-42c7-8b7e-250c3a03d3ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
