<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_Start date</name>
   <tag></tag>
   <elementGuidId>c3fd26fa-c9c3-4eb9-94ba-3352b8360c33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fromdate']/../..//input[@name='checkbox-']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5e74f61c-b13c-4b0b-b9c1-99a470f1646f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1714390617383</value>
      <webElementGuid>5d30473f-7e0e-45c4-8397-e09da8c5be75</webElementGuid>
   </webElementProperties>
</WebElementEntity>
