<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Last date</name>
   <tag></tag>
   <elementGuidId>4c775660-65a7-4438-b8bf-a3ca796d73a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#todate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='todate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;todate&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68379878-1a3e-457b-9327-4e535f4f74b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>b435e137-22dc-44ef-ae97-82993113cd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-leave-apply</value>
      <webElementGuid>6fce7280-0049-43ce-bc3b-84774837e0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>todate</value>
      <webElementGuid>6dffb9df-f47e-4ea8-b02c-f18822e1c116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>todate</value>
      <webElementGuid>34651d0b-3079-428e-bf11-919da498a2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>todate</value>
      <webElementGuid>46c2ddec-422a-4093-9b36-ddbdccaa50fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;todate&quot;)</value>
      <webElementGuid>430a98d4-53cb-4e66-b649-b167ba357ee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='todate']</value>
      <webElementGuid>9d97c5ae-8891-412f-b292-615447a13b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c6f6c87b-0704-4170-b76c-2dad5e08bab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'todate' and @name = 'todate']</value>
      <webElementGuid>e0797cbd-7b22-48b8-8761-2b7cee2ed282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
