<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Start date</name>
   <tag></tag>
   <elementGuidId>172755fb-b443-429a-a00f-1a9147e90fd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fromdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;fromdate&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe3efaf4-209e-4926-9aa7-98703e4e1082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>77b24989-7599-4d9e-b535-71f9168922fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-leave-apply</value>
      <webElementGuid>e53cdc00-c906-4061-b325-ce2ae42ce9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromdate</value>
      <webElementGuid>14ee2b37-8fff-4bf0-8533-220dd8d7d94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>fromdate</value>
      <webElementGuid>d0e9787e-5acf-4def-bf09-324353217f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fromdate</value>
      <webElementGuid>02de62ab-f72b-468e-9ed4-7335cc012a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromdate&quot;)</value>
      <webElementGuid>f6566eb6-0c33-4b43-aed9-9be8db5e8d54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fromdate']</value>
      <webElementGuid>261e1eee-6193-4380-a290-90851b34f232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>44331635-426d-4a9c-9074-e58e339ec024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'fromdate' and @name = 'fromdate']</value>
      <webElementGuid>bfd20ff2-6c7b-4cbb-a4f6-972b231c1588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
