<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Options_Select leave type</name>
   <tag></tag>
   <elementGuidId>0f978ab1-ddd2-4a84-9380-53079a879786</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name='leavetype']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>7a7b3a20-e45d-4179-bb5e-cf36343c3118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1714390913187</value>
      <webElementGuid>1b7bdd0c-f88e-47a0-b043-dee0cce25d1f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
