<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_Request leave popup heading</name>
   <tag></tag>
   <elementGuidId>2a88ec94-e73b-459b-bc74-174ac76c7cad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.headernameleave12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>464d8106-07ee-4aa6-a7a7-0ef99574dea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1714388862237</value>
      <webElementGuid>929d60e2-5969-4aa3-9495-e9fea4598d85</webElementGuid>
   </webElementProperties>
</WebElementEntity>
